apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chefbot-sim
  namespace: chefbot-sim
  labels:
    app: chefbot-sim
spec:
  ingressClassName: nginx
  rules:
    - host: chefbot-sim.development
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chefbot-sim
                port:
                  number: 80
