apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgresql-secret.yaml
  - postgresql-pvc.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - deployment.yaml
  - image-repository.yaml
  - service.yaml
  - ingress.yaml
