apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chefbot-sim
resources:
  - namespace.yaml
  - configmap.yaml
  - postgresql-secret.yaml
  - postgresql-pvc.yaml
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - deployment.yaml
  - image-repository.yaml
  - service.yaml
  - ingress.yaml

# Generate ConfigMap
configMapGenerator:
  - name: postgresql-config
    files:
      - postgresql-cdc-config/postgresql.conf
      - postgresql-cdc-config/pg_hba.conf
