apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - namespace.yaml
  - strimzi-helm-repo.yaml
  - strimzi-operator.yaml
  - kafka-metrics-configmap.yaml
  - kafka-nodepool.yaml
  - kafka-cluster.yaml
  - kafka-topics.yaml
