apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/chefbot-sim
  - image-policy.yaml
images:
  - name: ghcr.io/omar-ashraf1488/chefbot-sim
    newTag: v0.0.6 # {"$imagepolicy": "flux-system:chefbot-sim-image-policy:tag"}
patches:
  - path: configmap-patch.yaml
